function langStruct = getLanguageStrings()
    langStruct.english = struct( ...
        'FileMenu', 'File', ...
        'Menu_New', 'New...', ...
        'OpenMenu', 'Open...', ...
        'SaveMenu', 'Save', ...
        'SaveAsMenu', 'Save As...', ...
        'ExportMenu', 'Export', ...
        'PDFMenu', 'PDF', ...
        'ExitMenu', 'Exit', ...
        'EditMenu', 'Edit', ...
        'Menu_Undo', 'Undo', ...
        'Menu_Redo', 'Redo', ...
        'PreferencesMenu', 'Preferences', ...
        'HelpMenu', 'Help', ...
        'UserManualMenu', 'User Manual', ...
        'AboutMenu', 'About', ...
        'AboutMenu_2', 'About', ...
        'WebsiteMenu', 'Website', ...% Tabs
        'Tab_Setup', 'Setup', ...
        'BarTab', 'Bar', ...
        'BarprofileTab', 'Bar profile', ...
        'SupportsTab', 'Supports', ...
        'HingesTab', 'Hinges', ...
        'PointloadsTab', 'Point loads', ...
        'DistributedloadsTab', 'Distributed loads', ...
        'Tab_Results', 'Results', ...% Panels
        'BarSetupPanel', 'Bar Setup', ...
        'SupportsPanel', 'Supports', ...
        'Panel_Loads', 'Loads', ...
        'BearingReactionsPanel', 'Bearing Reactions', ...
        'CalculateForcesataspecificpointPanel', 'Calculate Forces at a specific point', ...
        'SumofsquarederrorsPanel', 'Sum of squared errors', ...
        'AdditionalDetailsPanel', 'Additional Details', ...% Labels
        'LengthSpinnerLabel', 'Length', ...
        'MaterialDropDownLabel', 'Material', ...
        'SteelDropDownLabel', 'Steel', ...
        'PositionSpinnerLabel', 'Position', ...
        'PositionSpinner_2Label', 'Position', ...
        'PositionSpinner_3Label', 'Position', ...
        'ForceSpinnerLabel', 'Force', ...
        'AngleSpinnerLabel', 'Angle', ...
        'StartPositionSpinnerLabel', 'Start Position', ...
        'EndPositionSpinnerLabel', 'End Position', ...
        'StartValueSpinnerLabel', 'Start Value', ...
        'PitchSpinnerLabel', 'Pitch', ...
        'SafetyyieldingEditFieldLabel', 'Safety yielding', ...
        'SafetyfractureEditFieldLabel', 'Safety fracture', ...
        'PositionEditFieldLabel', 'Position', ...
        'XForceEditFieldLabel', 'X-Force', ...
        'ZForceEditFieldLabel', 'Z-Force', ...
        'MomentEditFieldLabel', 'Moment', ...
        'ForceNNmEditFieldLabel', '[Force] N N/m', ...
        'PositionmLabel', '[Position] m', ...
        'AngledegEditFieldLabel', '[Angle] deg', ...% Buttons
        'Button_BarAdd', 'Add', ...
        'Button_BarprofileRektangle', '', ...
        'Button_BarprofileSquarehollow', '', ...
        'Button_BarprofileRound', '', ...
        'Button_BarprofileH', '', ...
        'Button_SupportAdd', 'Add', ...
        'Button_HingeAdd', 'Add', ...
        'Button_PointloadsAdd', 'Add', ...
        'Button_PointLoadsForce', '', ...
        'Button_PointloadsMoment', '', ...
        'Button_DistributedLoadsAdd', 'Add', ...
        'Button_DistributedLoadsConstant', '', ...
        'Button_DistributedLoadsLinear', '', ...
        'Button_DistributedLoadsQuadratic', '', ...
        'Button_SetupCalculate', 'Calculate!', ...% Tooltips
        'Spinner_PointLoadsAngle_Tooltip', '0° = leftward, 90° = upward', ...
        'Spinner_PointLoadsForce_Tooltip', 'Enter force value in Newton (N)', ...
        'Spinner_DistributedLoadsPitch_Tooltip', 'Defines the pitch for the distributed load', ...
        'Spinner_DistributedLoadsStartValue_Tooltip', 'Starting value of the distributed load in N/m', ...
        'Button_HingeShearforce_Tooltip', 'Coming soon', ...
        'Button_HingeNormalforce_Tooltip', 'Coming soon', ...% Placeholders
        'Spinner_BarprofileA_Placeholder', 'A  ', ...
        'Spinner_BarprofileB_Placeholder', 'B  ', ...% UI Axis Labels
        'UIAxes_Setup', 'Setup', ...
        'UIAxes_Setup_XLabel', 'X', ...
        'UIAxes_Setup_YLabel', 'Z', ...
        'UIAxes_ResultsNormalForce', 'Normal-Force', ...
        'UIAxes_ResultsNormalForce_XLabel', 'X', ...
        'UIAxes_ResultsNormalForce_YLabel', 'Force (N)', ...
        'UIAxes_ResultsShearForce', 'Shear-Force', ...
        'UIAxes_ResultsShearForce_XLabel', 'X', ...
        'UIAxes_ResultsShearForce_YLabel', 'Force (N)', ...
        'UIAxes_ResultsMoment', 'Moment', ...
        'UIAxes_ResultsMoment_XLabel', 'X', ...
        'UIAxes_ResultsMoment_YLabel', 'Moment (Nm)' ...
        );

    % German translations (you can add more)
    langStruct.german = struct( ...
        'FileMenu', 'Datei', ...
        'Menu_New', 'Neu...', ...
        'OpenMenu', 'Öffnen...', ...
        'SaveMenu', 'Speichern', ...
        'SaveAsMenu', 'Speichern unter...', ...
        'ExportMenu', 'Exportieren', ...
        'PDFMenu', 'PDF', ...
        'ExitMenu', 'Beenden', ...
        'EditMenu', 'Bearbeiten', ...
        'Menu_Undo', 'Rückgängig', ...
        'Menu_Redo', 'Wiederholen', ...
        'PreferencesMenu', 'Einstellungen', ...
        'HelpMenu', 'Hilfe', ...
        'UserManualMenu', 'Benutzerhandbuch', ...
        'AboutMenu', 'Über', ...
        'AboutMenu_2', 'Über', ...
        'WebsiteMenu', 'Website', ...% Tabs
        'Tab_Setup', 'Einstellungen', ...
        'BarTab', 'Balken', ...
        'BarprofileTab', 'Balkenprofil', ...
        'SupportsTab', 'Stützen', ...
        'HingesTab', 'Gelenke', ...
        'PointloadsTab', 'Punktlasten', ...
        'DistributedloadsTab', 'Verteilte Lasten', ...
        'Tab_Results', 'Ergebnisse', ...% Panels
        'BarSetupPanel', 'Balkeneinstellung', ...
        'SupportsPanel', 'Stützen', ...
        'Panel_Loads', 'Lasten', ...
        'BearingReactionsPanel', 'Lagerreaktionen', ...
        'CalculateForcesataspecificpointPanel', 'Berechne Kräfte an einem Punkt', ...
        'SumofsquarederrorsPanel', 'Summe der quadrierten Fehler', ...
        'AdditionalDetailsPanel', 'Zusätzliche Details', ...% Labels
        'LengthSpinnerLabel', 'Länge', ...
        'MaterialDropDownLabel', 'Material', ...
        'SteelDropDownLabel', 'Stahl', ...
        'PositionSpinnerLabel', 'Position', ...
        'PositionSpinner_2Label', 'Position', ...
        'PositionSpinner_3Label', 'Position', ...
        'ForceSpinnerLabel', 'Kraft', ...
        'AngleSpinnerLabel', 'Winkel', ...
        'StartPositionSpinnerLabel', 'Startposition', ...
        'EndPositionSpinnerLabel', 'Endposition', ...
        'StartValueSpinnerLabel', 'Startwert', ...
        'PitchSpinnerLabel', 'Steigung', ...
        'SafetyyieldingEditFieldLabel', 'Sicherheitsfaktor Streckgrenze', ...
        'SafetyfractureEditFieldLabel', 'Sicherheitsfaktor Bruch', ...
        'PositionEditFieldLabel', 'Position', ...
        'XForceEditFieldLabel', 'X-Kraft', ...
        'ZForceEditFieldLabel', 'Z-Kraft', ...
        'MomentEditFieldLabel', 'Moment', ...
        'ForceNNmEditFieldLabel', '[Kraft] N N/m', ...
        'PositionmLabel', '[Position] m', ...
        'AngledegEditFieldLabel', '[Winkel] Grad', ...% Buttons
        'Button_BarAdd', 'Hinzufügen', ...
        'Button_SupportAdd', 'Hinzufügen', ...
        'Button_HingeAdd', 'Hinzufügen', ...
        'Button_PointloadsAdd', 'Hinzufügen', ...
        'Button_DistributedLoadsAdd', 'Hinzufügen', ...
        'Button_SetupCalculate', 'Berechnen!', ...
        'Button_BarprofileRektangle', '', ...
        'Button_BarprofileSquarehollow', '', ...
        'Button_BarprofileRound', '', ...
        'Button_BarprofileH', '', ...
        'Button_PointLoadsForce', '', ...
        'Button_PointloadsMoment', '', ...
        'Button_DistributedLoadsConstant', '', ...
        'Button_DistributedLoadsLinear', '', ...
        'Button_DistributedLoadsQuadratic', '', ...% Tooltips
        'Spinner_PointLoadsAngle_Tooltip', '0° = links, 90° = nach oben', ...
        'Spinner_PointLoadsForce_Tooltip', 'Kraftwert in Newton (N) eingeben', ...
        'Spinner_DistributedLoadsPitch_Tooltip', 'Definiert die Steigung für die verteilte Last', ...
        'Spinner_DistributedLoadsStartValue_Tooltip', 'Startwert der verteilten Last in N/m', ...
        'Button_HingeShearforce_Tooltip', 'Kommt bald', ...
        'Button_HingeNormalforce_Tooltip', 'Kommt bald', ...% Placeholders
        'Spinner_BarprofileA_Placeholder', 'A  ', ...
        'Spinner_BarprofileB_Placeholder', 'B  ', ...% UI Axis Labels
        'UIAxes_Setup', 'Einstellungen', ...
        'UIAxes_Setup_XLabel', 'X', ...
        'UIAxes_Setup_YLabel', 'Z', ...
        'UIAxes_ResultsNormalForce', 'Normalkraft', ...
        'UIAxes_ResultsNormalForce_XLabel', 'X', ...
        'UIAxes_ResultsNormalForce_YLabel', 'Kraft (N)', ...
        'UIAxes_ResultsShearForce', 'Scherkraft', ...
        'UIAxes_ResultsShearForce_XLabel', 'X', ...
        'UIAxes_ResultsShearForce_YLabel', 'Kraft (N)', ...
        'UIAxes_ResultsMoment', 'Moment', ...
        'UIAxes_ResultsMoment_XLabel', 'X', ...
        'UIAxes_ResultsMoment_YLabel', 'Moment (Nm)' ...
        );
end
